version: "3"
services:
  webserver:
    image: nginx:latest
    working_dir: /application
    container_name: nginx-php-webserver      
    volumes:
        - ../../www:/www
        - ../../script/:/script/
        - ../../bin/certbot-auto:/usr/local/bin/certbot-auto
        - ../../config/sites-available/:/etc/nginx/sites-available/
        - ../../config/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
        - ../../config/fastcgi/fastcgi_params:/etc/nginx/fastcgi_params
        - ../../ssl/letsencrypt/:/etc/letsencrypt/
        - ../../ssl/ssl/:/etc/ssl/
        - ../../log:/log
    ports:
        - "80:80"
        - "443:443"
    restart: always


  php-app:
    build: ../../docker/php-fpm/
    working_dir: /application
    container_name: php-fpm7.3      
    volumes:
        - ../../www:/www
        - ../../config/pool.d/:/etc/php/7.3/fpm/pool.d
        - ../../config/php_ini/php.ini:/etc/php/7.3/fpm/php.ini
        - ../../log:/log
    restart: always
